packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  # all packages in subdirs of components/
  # - "components/**"
  - "play" # 运行查看组件
  - "docs" # 文档
  # exclude packages that are inside test directories
  - "!**/test/**"
